Repository voyagegroup/ingred-ui, pull requests merged in 2021-06, with the labels that each got.

#371 [Popover]モーダルを開くときに座標を更新するように
  src/components/Popover/Popover.tsx
Labels: bug

#372 [MultipleFilter]カード内のDesignを修正 & placeholderを変更可能に
  src/components/MultipleFilter/MultipleFilter.stories.tsx
  src/components/MultipleFilter/MultipleFilter.tsx
  src/components/MultipleFilter/internal/EditFilterCard/EditFilterCard.tsx
  src/components/MultipleFilter/internal/FilterCard/FilterCard.tsx
Labels: enhancement

#375 release v7.27.0
  CHANGELOG.md
  package.json
Labels: release

#392 release v7.28.0
  CHANGELOG.md
  package.json
Labels: release

#394 Storybookで型が表示されない問題を対応
  .storybook/main.js
  package.json
  yarn.lock
Labels: bug, dependencies

#397 release v7.28.1
  CHANGELOG.md
  package.json
Labels: release

#400 release v7.29.0
  CHANGELOG.md
  package.json
Labels: release

#401 <DataTable />チェックまわりのバグ改修
  src/components/DataTable/DataTable.tsx
  src/components/DataTable/internal/CellCheckbox/CellCheckbox.tsx
  src/components/DataTable/internal/CellRadio/CellRadio.tsx
Labels: bug

#402 release v7.29.1
  CHANGELOG.md
  package.json
Labels: release
