Repository voyagegroup/ingred-ui, pull requests merged in 2021-04, with the labels that each got.

#282 CHANGELOGを出力した
  CHANGELOG.md
Labels: wontfix

#288 MenuにWarnTextを追加
  src/components/ContextMenu/ContextMenu.stories.mdx
  src/components/ContextMenu/__tests__/ContextMenu.test.tsx
  src/components/ContextMenu/__tests__/__snapshots__/ContextMenu.test.tsx.snap
  src/components/DropdownButton/DropdownButton.stories.tsx
  src/components/DropdownButton/__tests__/DropDownButton.test.tsx
  src/components/DropdownButton/__tests__/__snapshots__/DropDownButton.test.tsx.snap
  src/components/Menu/Menu.stories.mdx
  src/components/MenuList/MenuList.stories.mdx
  src/components/MenuList/MenuList.tsx
  src/components/MenuList/__tests__/MenuList.test.tsx
  src/components/MenuList/__tests__/__snapshots__/MenuList.test.tsx.snap
  src/components/MenuList/styled.ts
Labels: ガーデニング, フロント

#295 release作業をGitHub Actionsで実行できるようにする
  .circleci/config.yml
  .github/workflows/publish.yaml
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  README.md
  ci.mk
Labels: enhancement

#298 releaseのPRのリンク修正
  .github/workflows/release.yaml
Labels: bug

#299 release & publishのflowを修正する
  .github/workflows/publish.yaml
  .github/workflows/release.yaml
Labels: bug

#301 release v7.21.2
  CHANGELOG.md
  package.json
Labels: release

#296 MenuにGroupを追加
  src/components/ContextMenu/__tests__/__snapshots__/ContextMenu.test.tsx.snap
  src/components/DropdownButton/__tests__/__snapshots__/DropDownButton.test.tsx.snap
  src/components/MenuList/MenuList.stories.mdx
  src/components/MenuList/MenuList.tsx
  src/components/MenuList/__tests__/MenuList.test.tsx
  src/components/MenuList/__tests__/__snapshots__/MenuList.test.tsx.snap
  src/components/MenuList/styled.ts
Labels: ガーデニング, フロント

#287 MenuにWarnTextとGroupを追加
  src/components/ContextMenu/ContextMenu.stories.mdx
  src/components/ContextMenu/__tests__/ContextMenu.test.tsx
  src/components/ContextMenu/__tests__/__snapshots__/ContextMenu.test.tsx.snap
  src/components/DropdownButton/DropdownButton.stories.tsx
  src/components/DropdownButton/__tests__/DropDownButton.test.tsx
  src/components/DropdownButton/__tests__/__snapshots__/DropDownButton.test.tsx.snap
  src/components/Menu/Menu.stories.mdx
  src/components/MenuList/MenuList.stories.mdx
  src/components/MenuList/MenuList.tsx
  src/components/MenuList/__tests__/MenuList.test.tsx
  src/components/MenuList/__tests__/__snapshots__/MenuList.test.tsx.snap
  src/components/MenuList/styled.ts
Labels: ガーデニング, フロント

#305 release v7.22.0
  CHANGELOG.md
  package.json
Labels: release

#307 storybookにINGRED-UIのfaviconを設定
  .gitignore
  .storybook/manager-head.html
  .storybook/manager.js
Labels: enhancement

#308 testとlintがmasterに向いてないPRでも実行されるようにした
  .github/workflows/check.yaml
Labels: enhancement

#306 Storybookの見た目をINGRED UI仕様にする
  .gitignore
  .storybook/manager-head.html
  .storybook/manager.js
  .storybook/myTheme.js
  assets/IngredUi/faviconIngredUi.png
  assets/IngredUi/logoIngredUi.png
Labels: enhancement

#292 Select label design
  src/components/Select/Select.tsx
  src/components/Select/__tests__/__snapshots__/Select.test.tsx.snap
  src/components/Select/internal/ClearIndicator/ClearIndicator.tsx
  src/components/Select/internal/ClearIndicator/styled.ts
  src/components/Select/internal/MultiValueRemove/MultiValueRemove.tsx
Labels: enhancement

#311 release v7.22.1
  CHANGELOG.md
  package.json
Labels: release

#330 react-hook-formをdependenciesへ
  package.json
Labels: bug

#331 成果物の動作検証ができる環境を作る
  testEnv/.gitignore
  testEnv/README.md
  testEnv/package.json
  testEnv/public/favicon.ico
  testEnv/public/index.html
  testEnv/public/logo192.png
  testEnv/public/logo512.png
  testEnv/public/manifest.json
  testEnv/public/robots.txt
  testEnv/src/App.tsx
  testEnv/src/index.tsx
  testEnv/src/logo.svg
  testEnv/src/react-app-env.d.ts
  testEnv/tsconfig.json
  testEnv/yarn.lock
Labels: enhancement
