Repository voyagegroup/ingred-ui, pull requests merged in 2021-05, with the labels that each got.

#339 release v7.23.0
  CHANGELOG.md
  package.json
Labels: release

#343 [MultipleFilter]編集したときにonChangeが発火するように
  src/components/MultipleFilter/MultipleFilter.tsx
Labels: bug

#347 release v7.24.0
  CHANGELOG.md
  package.json
Labels: release

#349 [MultipleFilter]線の色を修正
  src/components/MultipleFilter/internal/EditFilterCard/EditFilterCard.tsx
  src/components/MultipleFilter/internal/EditFilterCard/styled.ts
  src/components/MultipleFilter/internal/FilterCard/FilterCard.tsx
  src/components/MultipleFilter/internal/FilterCard/styled.ts
Labels: フロント

#358 release v7.25.0
  CHANGELOG.md
  package.json
Labels: release

#351 [MultipleFilter]テキストをより自由に
  src/components/MultipleFilter/MultipleFilter.stories.tsx
  src/components/MultipleFilter/MultipleFilter.tsx
  src/components/MultipleFilter/internal/EditFilterCard/EditFilterCard.tsx
  src/components/MultipleFilter/internal/FilterCard/FilterCard.tsx
  src/components/MultipleFilter/internal/Label/Label.tsx
  src/components/MultipleFilter/types/index.ts
Labels: enhancement

#366 Release Noteを自動生成する
  .github/workflows/release.yaml
  .gitignore
  ci.mk
Labels: enhancement

#367 release v7.26.0
  CHANGELOG.md
  package.json
Labels: release

#368 Release PRの説明文のリンクを修正
  .github/workflows/release.yaml
Labels: bug
